### ISSUE TITLE
non-character argument

### ISSUE THREAD

**Issue by skiniry** [boboppie/RiboTaper#1]
Hi, When running the script  NONCCDS_orf_finder.R I keep getting this error:

[1] "--- non-CCDS ORF finding --- Mon Feb  8 11:22:52 2016"
Error in { : task 1 failed - "non-character argument"
Calls: %dopar% -> <Anonymous>
Execution halted

My bedtools version is 2.17, samtools is 0.1.19 and R is 3.0.2. I also tried with R-3.0.1 but had the same error. The exact command I give to the command line is:

./scripts/NONCCDS_orf_finder.R ./annotations ./scripts/ /usr/bin/ 6

**Comment by boboppie** [comment]
Dear @skiniry,

This is not an official Github repo of RiboTaper. Could you please contact the author directly via the email provided in the paper.

Best wishes
